---
name: 'test_deploy'

'on':
  push:
    branches:
      - 'main'

jobs:
  pypi_deploy:

    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout repo'
        uses: 'actions/checkout@v2'

      - name: 'Set up Python 3.8'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: 'Install pip and Poetry'
        run: |
          python -m pip install --upgrade pip poetry
          poetry config virtualenvs.in-project true

      - name: Get full python version
        id: full-python-version
        run: |
          echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

      - name: 'Cache poetry'
        uses: 'actions/cache@v1'
        with:
          path: '.venv'
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: 'Install dependencies'
        run: 'poetry install'

      - name: 'Setup PyPi credential'
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TEST_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi "$PYPI_TOKEN"

      - name: 'Package build'
        run: 'poetry build'

      - name: 'Publish package to PyPi'
        run: 'poetry publish --dry-run -r testpypi'
